apiVersion: v1
kind: Namespace
metadata:
  name: gvbngvjngjgjg-staging
  labels:
    environment-id: env_7a8bc675-be19-49ba-af15-56cb0eb5448c
    project-id: project_1009d2b5-3d34-447c-a723-a8cc1a767f26
    project-name: gvbngvjngjgjg
    environment-name: staging
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
